### ISSUE TITLE
PHP Notice:  Undefined offset usb_model.php on line 212

### ISSUE THREAD

**Issue by precursorca** [munkireport/usb#5] opened 2020-09-30 12:58 UTC
I see this in my web logs (i.p. obscured) with x's):
[php7:notice] [pid 92207] [client x.x.x.x:49823] PHP Notice:  Undefined offset: 1 in /Users/Shared/munkireport-php/vendor/munkireport/usb/usb_model.php on line 212

**Comment by tuxudo** [comment] 2021-04-02 13:05
Caused by a USB device not having a vendor ID. Fixed by adding a check for vendor ID before processing it to extract the manufacturer. Should be resolved now

**Closed as completed** 2021-09-22 03:08 UTC
